name: Run Topics Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  topics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Runs python script
        run: python ./.github/workflows/topics.py
      - name: Commit readme
        run: |
          git config --global user.name 'Kevin Lago'
          git config --global user.email 'kevinthelago@gmail.com'
          git commit -am "Auto Update Readme"
          git push
