name: Run Topics Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  topics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Runs python script
        run: python ./.github/workflows/topics.py
      - name: Stage Changes
        run: git add .
      - name: Commit Changes
        run: git commit -m "Auto Updating Markdown"
      - name: Push Changes
        run: git push origin HEAD:master
